  <table width="100%"  border="0" cellspacing="0" cellpadding="0" summary="table for layout">
  <tr valign="middle">
    <td><img src="/images/global/logo.gif" alt="The National Archives" width="118" height="73" align="left" /></td>
	<td><img height="44" alt="Public Information Films" src="/images/appnames/films_popupheader.gif"
						width="240" /></td>
	<td valign="top" >
      <table width="170" align="right" border="0" cellspacing="0" cellpadding="0" summary="table for layout">
        <tr>
          <td valign="top">
						<noscript>To print (for PC users), press <b>Ctrl</b> 
						+ <b>P</b> key.<br />
						To print (for MAC users), press <b>Command</b> + <b>P</b> 
						key.<br />
						</noscript>
						<a href="#" onkeypress="this.onclick()" onclick="tna_print()"><img src="/images/buttons/popup_print.gif" alt="Print page" width="64" height="20" border="0" /></a>
		  </td>
          <td><img src="/images/pixels/pixeltrans.gif" alt="" width="10" height="8" /></td>
					<td valign="top"><a href="javascript:window.close();" accesskey="k"><img src="/images/buttons/popup_close.gif" alt="Close window" border="0" width="106" height="20" align="right" /></a></td>
        </tr>
      </table>
	</td>
    <td width="2%">&nbsp;</td>
  </tr>
  <tr>
				<td class="thindots" colspan="4"><img height="1" alt="" border="0" src="/images/pixels/pixeltrans.gif" width="1" /></td>
			</tr>
</table>
<br/>