<tr>
      <td class="index_bg_head" width="10%">&nbsp;</td>
    <td class="index_bg_head" width="80%">
	<table width="750" border="0" cellpadding="0" cellspacing="0">
  <tr>
    <td><a href="/films/"><img src="/films/images/index_head.gif" width="375" height="51" alt="Public Information Films" border="0" /></a></td>
    </tr>
	</table>
	</td>
	<td class="index_bg_head" width="10%">&nbsp;</td>
  </tr>