<table width="100%" border="0" cellpadding="2" cellspacing="2">
      <tr>
        <td width="80"><a href="/films/1945to1951/popup/pop_itb01.htm"><img src="/films/1945to1951/popup/images/itb/thumbs/01.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
      <td width="80"><a href="/films/1945to1951/popup/pop_itb02.htm" ><img src="/films/1945to1951/popup/images/itb/thumbs/02.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
       </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_itb03.htm"><img src="/films/1945to1951/popup/images/itb/thumbs/03.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_itb04.htm"><img src="/films/1945to1951/popup/images/itb/thumbs/04.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_itb05.htm"><img src="/films/1945to1951/popup/images/itb/thumbs/05.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_itb06.htm"><img src="/films/1945to1951/popup/images/itb/thumbs/06.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_itb07.htm"><img src="/films/1945to1951/popup/images/itb/thumbs/07.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_itb08.htm"><img src="/films/1945to1951/popup/images/itb/thumbs/08.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
    </table>