<table width="100%" border="0" cellpadding="2" cellspacing="2">
      <tr>
        <td width="80"><a href="/films/1945to1951/popup/pop_twj01.htm"><img src="/films/1945to1951/popup/images/twj/thumbs/01.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
      <td width="80"><a href="/films/1945to1951/popup/pop_twj02.htm" ><img src="/films/1945to1951/popup/images/twj/thumbs/02.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
       </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_twj03.htm"><img src="/films/1945to1951/popup/images/twj/thumbs/03.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_twj04.htm"><img src="/films/1945to1951/popup/images/twj/thumbs/04.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_twj05.htm"><img src="/films/1945to1951/popup/images/twj/thumbs/05.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_twj06.htm"><img src="/films/1945to1951/popup/images/twj/thumbs/06.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_twj07.htm"><img src="/films/1945to1951/popup/images/twj/thumbs/07.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_twj08.htm"><img src="/films/1945to1951/popup/images/twj/thumbs/08.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
    </table>