<table width="100%" border="0" cellpadding="2" cellspacing="2">
      <tr>
        <td width="80"><a href="/films/1945to1951/popup/pop_cyvgh01.htm"><img src="/films/1945to1951/popup/images/cyvgh/thumbs/01.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
      <td width="80"><a href="/films/1945to1951/popup/pop_cyvgh02.htm" ><img src="/films/1945to1951/popup/images/cyvgh/thumbs/02.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
       </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_cyvgh03.htm"><img src="/films/1945to1951/popup/images/cyvgh/thumbs/03.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_cyvgh04.htm"><img src="/films/1945to1951/popup/images/cyvgh/thumbs/04.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_cyvgh05.htm"><img src="/films/1945to1951/popup/images/cyvgh/thumbs/05.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_cyvgh06.htm"><img src="/films/1945to1951/popup/images/cyvgh/thumbs/06.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_cyvgh07.htm"><img src="/films/1945to1951/popup/images/cyvgh/thumbs/07.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_cyvgh08.htm"><img src="/films/1945to1951/popup/images/cyvgh/thumbs/08.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
    </table>