<table width="100%" border="0" cellpadding="2" cellspacing="2">
      <tr>
        <td width="80"><a href="/films/1945to1951/popup/pop_bc01.htm"><img src="/films/1945to1951/popup/images/bc/thumbs/01.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
      <td width="80"><a href="/films/1945to1951/popup/pop_bc02.htm" ><img src="/films/1945to1951/popup/images/bc/thumbs/02.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
       </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_bc03.htm"><img src="/films/1945to1951/popup/images/bc/thumbs/03.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_bc04.htm"><img src="/films/1945to1951/popup/images/bc/thumbs/04.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_bc05.htm"><img src="/films/1945to1951/popup/images/bc/thumbs/05.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_bc06.htm"><img src="/films/1945to1951/popup/images/bc/thumbs/06.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_bc07.htm"><img src="/films/1945to1951/popup/images/bc/thumbs/07.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_bc08.htm"><img src="/films/1945to1951/popup/images/bc/thumbs/08.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
    </table>