<table width="100%" border="0" cellpadding="2" cellspacing="2">
      <tr>
        <td width="80"><a href="/films/1945to1951/popup/pop_pgtw01.htm"><img src="/films/1945to1951/popup/images/pgtw/thumbs/01.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
      <td width="80"><a href="/films/1945to1951/popup/pop_pgtw02.htm" ><img src="/films/1945to1951/popup/images/pgtw/thumbs/02.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
       </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_pgtw03.htm"><img src="/films/1945to1951/popup/images/pgtw/thumbs/03.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_pgtw04.htm"><img src="/films/1945to1951/popup/images/pgtw/thumbs/04.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_pgtw05.htm"><img src="/films/1945to1951/popup/images/pgtw/thumbs/05.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_pgtw06.htm"><img src="/films/1945to1951/popup/images/pgtw/thumbs/06.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
      <tr>
        <td><a href="/films/1945to1951/popup/pop_pgtw07.htm"><img src="/films/1945to1951/popup/images/pgtw/thumbs/07.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        <td><a href="/films/1945to1951/popup/pop_pgtw08.htm"><img src="/films/1945to1951/popup/images/pgtw/thumbs/08.jpg" width="80" height="80" border="0" alt="Film screenshot thumbnail" /></a></td>
        </tr>
    </table>