</table></td>
									  </tr>
										<tr>
											<td align="right">&nbsp;</td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </div>
      <!-- end Module 16: tabbed table with columns -->			</td>
      <td>&nbsp;</td>
    </tr>
    <!-- end wrap ASP code for IR List homepage -->
    <!-- start wrap ASP code for list 10 results -->
    <!-- end wrap ASP code for list 10 results -->
  </table>
  <!--#include virtual="/includes/footer.inc" -->
</div>

<script src="/accessions/js/accessibility-script.js"></script>
</body>
</html>
