<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-T8DSWV');</script>
<!-- End Google Tag Manager -->

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="/css/tnans4.css" type="text/css" rel="stylesheet" />
<style type="text/css">
<!--
@import url("/css/tnaie4plus.css");
-->
</style>
<style type="text/css">
  <!--
  @import "/css/null.css?\"\{";
  @import "/css/tna6plus.css";
  -->
  </style>
<script type="text/javascript" src="/script/jquery-latest.js"></script>
<script language="JavaScript" type="text/javascript" src="/script/utils.js"></script>
<link href="/css/tna-accessions.css" type="text/css" rel="stylesheet" />
<script language="JavaScript" type="text/javascript" src="/scripts/tna-accessions.js"></script>

</head>
<body>
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T8DSWV"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
<div id="logosearch">
			<!--#include virtual="/includes/logosearchcms.inc" -->
			<!--menu goes here -->
			<!--#include virtual="/includes/menu.inc" -->
			<!-- end of menu -->
		</div>

<div id="content">
  <table width="100%" cellpadding="0" cellspacing="0" border="0">
    <tr>
      <td width="2%">&nbsp;</td>
      <td valign="top">
        <div id="breadcrumb">You are here: <a href="/" class="breadcrumbs">Home</a> &gt; <a href="/help-with-your-research/" class="breadcrumbs">Help with your research</a>
          &gt; <a href="/accessions/default.htm" class="breadcrumbs">Accessions to repositories</a> &gt;