<script src="/script/global-search.js" type="text/javascript"></script>
<div id="searchTools">
        <div id="linksToSearchForms"><a href="/search/results">Search the website</a> | <a href="http://www.discovery.nationalarchives.gov.uk">Search the catalogue</a></div>
    <div id="tnaSearchWrapper">
         <div id="userControls"><a href="/legal/cookies.htm">Cookie policy</a> | <div id="hdr-personalisation"><a href="/Search/Login.aspx">MyPage (not signed in)</a></div></div>
        <div id="tnaSearchWrapperInner">   
        <form action="/search/results" method="get" id="globalSearch">
            <label for="tnaSearch">Search the archives</label>
            <span id="searchOptionToggler">Search our website</span>
            <span id="containingBox">
            <input type="text" id="tnaSearch" name="_q" required aria-required="true" />
            <input type="image" id="tnaSearchSubmit" src="/images/global/searchButtonImage.png"/>
            </span>
        </form>
        </div> 
        <div id="searchFormOptions" class="noJavaScript">
                <ul id="searchOptions">
                    <li>Search our website</li>
                    <li>Search our records</li>
                </ul>
            </div>         
    </div>
</div> 
</div>

<div class="ftr-clear"></div>
<div id="ftr">
    <div class="ftr-footer-spacer"></div>
    <div id="ftr-footer-links-wrapper">
        <div id="ftr-getting-in-touch">
            <h4>Find out more</h4>
            <ul>
                <li><a href="/contact">Contact us<span class="red-arrow"></span></a></li>
                <li><a href="/pressroom/">Press room<span class="red-arrow"></span></a></li>
                <li><a href="/jobs/">Jobs and careers<span class="red-arrow"></span></a></li>
		<li><a href="http://labs.nationalarchives.gov.uk/zeitgeist/">Digital trends 2012<span class="red-arrow"></span></a></li>
            </ul>
        </div>


 <div id="ftr-about-us">
            <h4>Legal</h4>
            <ul>              
                <li><a href="/legal/">Terms of use<span class="red-arrow"></span></a></li>
                <li><a href="/legal/cookies.htm">Cookies<span class="red-arrow"></span></a></li>
                <li><a href="/foi\default.htm">Freedom of information<span class="red-arrow"></span></a></li>
		<li><a href="/about/transparency.htm">Transparency<span class="red-arrow"></span></a></li>
            </ul>
        </div>

<div id="ftr-websites">
            <h4>Websites</h4>
            <ul>
 		<li><a href="http://blog.nationalarchives.gov.uk/">Blog<span class="red-arrow"></span></a></li>
		<li><a href="http://media.nationalarchives.gov.uk/">Podcasts and videos<span class="red-arrow"></span></a></li>
                <li><a href="http://www.legislation.gov.uk/">Legislation.gov.uk<span class="red-arrow"></span></a></li>
                <li><a href="https://www.gov.uk/" target="blank">GOV.UK<span class="red-arrow"></span></a></li>

            </ul>
        </div>


        <div id="ftr-site-help">
            <h4>Site help</h4>
            <ul>
		<li><a href="/help/">Help<span class="red-arrow"></span></a></li>
		<li><a href="/help/atoz.htm">Website A-Z index<span class="red-arrow"></span></a></li>
                <li><a href="/help/accessibility.htm">Accessibility<span class="red-arrow"></span></a></li>
		<li><a href="/help/sitemap.htm">Site map<span class="red-arrow"></span></a></li>
            </ul>
        </div>


       
        
    </div>

    <div class="ftr-footer-spacer"></div>
    <div id="ftr-footer-contact-bar">
        The National Archives, Kew, Richmond, TW9 4DU. <a href="/contact-us/">Contact us</a>
    </div>
</div>
