			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="2%">&nbsp;</td>
					<td valign="top">
					<table width="100%" border="0" cellspacing="0" cellpadding="0" summary="table for layout" style="margin-top: 7px; vertical-align: top;">
        <tr>
          <td width="21%" valign="bottom"><img src="/images/appnames/hospitalrecords_pic_top.jpg" alt="Montage of three nurses. All images &copy; Wellcome Library, London. References: L0010490, L0018470, L0010789." width="137" height="56" align="right" /></td>
          <td valign="top" width="60%" align="left"><a href="/hospitalrecords/default.asp"><img src="/images/appnames/hospitalrecords_heading.gif" alt="Hospital Records Database" width="360" height="45" border="0" /></a></td>
          <td width="2%" class="appmenudivider"><img src="/images/pixels/pixeltrans.gif" alt="" width="10" height="50" /></td>
          <td width="17%" valign="top"><div align="right">
              <table width="167" border="0" cellpadding="0" cellspacing="0" summary="Hospital Records Database menu">
                <tr>
                  <td width="90"><a href="/hospitalrecords/default.asp"><img src="/images/appmenu/welcome_off.gif" alt="Welcome (Hospital Records home page)" width="90" height="20" border="0" /></a></td>
                  <td width="77"><img src="/images/appmenu/about_on.gif" alt="About Hospital Records" width="57" height="20" border="0" /></td>
                </tr>
                <tr>
                  <td width="90"><a href="/hospitalrecords/search.asp"><img src="/images/appmenu/search_off.gif" width="72" height="20" alt="Search" border="0" /></a></td>
                  <td width="77"><a href="/help/hospitalrecords/default.htm" target="popup" onKeyPress="this.onlick()" onClick="PRO_openPopupWindow('/help/hospitalrecords/default.htm','popup','650','400','toolbar=yes,menubar=yes,scrollbars=yes,resizable=yes','yes');return false"><img src="/images/appmenu/help_off.gif" width="52" height="20" border="0" alt="Help - opens in a new window" /></a></td>
                </tr>
              </table>
            </div></td>
        </tr>
        <tr>
          <td width="19%" valign="top" class="parchmentnav"><img src="/images/appnames/hospitalrecords_pic_bottom.jpg" align="right" alt="" width="137" height="17" /></td>
          <td colspan="3" class="parchmentnav"><div>&nbsp;</div></td>
        </tr>
      </table>
								</td>
					<td width="2%">&nbsp;</td>
				</tr>
			</table>