		<div class="hr-inset">

			<a href="/humanrights/documents/glossary.htm"><img src="/images/humanrights/btn-glossary.gif" height="38" width="203" alt="glossary" /></a>

			<a href="/humanrights/documents/default.htm"><img src="/images/humanrights/btn-doc-index.gif" height="38" width="203" alt="document index" /></a>

			<p>A complete list of all the supporting documents for the time periods between 1215 and 1945.</p>

		</div>
		
	


