<div id="hdr">
	<script src="/script/hdr-search-utils.js" type="text/javascript"></script>
	
	<div id="hdr-logo-holder">
	<a href="/default.htm" title="The National Archives"><img src="/images/global/hdr-logo.gif" alt="The National Archives" title="The National Archives" /></a>
	</div>
	<ul class="hidden">
		<li><a href="#content" accesskey="s">Skip to Content</a></li>
		<li><a href="/help/accesskeys.htm" accesskey="0">List of Access Keys</a></li>
	</ul>

</div>