<div id="hdr">
	
	<script src="/script/jquery-latest.js" type="text/javascript"></script>
	<script src="/script/global-search.js" type="text/javascript"></script>
	<script src="/script/hdr-search-utils.js" type="text/javascript"></script>
	
	<div id="hdr-logo-holder">
	<a href="/default.htm" title="The National Archives"><img src="/images/global/hdr-logo.gif" alt="The National Archives" title="The National Archives" /></a>
	</div>
	<ul class="hidden">
		<li><a href="#content" accesskey="s">Skip to Content</a></li>
		<li><a href="/help/accesskeys.htm" accesskey="0">List of Access Keys</a></li>
	</ul>
	
<div id="searchTools">
        <div id="linksToSearchForms"><a href="/search/results">Search the website</a> | <a href="http://www.discovery.nationalarchives.gov.uk">Search the catalogue</a></div>
    <div id="tnaSearchWrapper">
        <!-- div id="userControls"><a href="/legal/cookies.htm">Cookie policy</a> | <div id="hdr-personalisation"><a href="/Search/Login.aspx">MyPage (not signed in)</a></div></div -->
        <div id="tnaSearchWrapperInner">   
        <form action="/search/results" method="get" id="globalSearch">
            <label for="tnaSearch">Search the archives</label>
            <span id="searchOptionToggler">Search our website</span>
            <span id="containingBox">
            <input type="text" id="tnaSearch" name="_q" required aria-required="true" />
            <input type="image" id="tnaSearchSubmit" src="/images/global/searchButtonImage.png"/>
            </span>
        </form>
        </div> 
        <div id="searchFormOptions" class="noJavaScript">
                <ul id="searchOptions">
                    <li>Search our website</li>
                    <li>Search our records</li>
                </ul>
            </div>         
    </div>
</div> 


</div>
</div>