  <div class="mega-menu" role="navigation">
    <section class="row">
      <nav class="col mega-menu-group clr">
        <div>
				<h3><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about">About us</a></h3>
					<ul>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/our-role/">Our role</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/visit-us/">Visit us</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/visit-us/opening-times/">Opening times</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/aboubbt/visit-us/whats-on/">What's on</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/visit-us/whats-on/exhibitions/">Exhibitions</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/visit-us/whats-on/events/">Events</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/get-involved/">Get involved</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/news/">News</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/about/commercial-opportunities/">Commercial opportunities</a></li>
					</ul>
        </div>
      </nav>
      <nav class="col mega-menu-group clr">
        <div>
				<h3><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/education/">Education</a></h3>
					<ul>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/education/sessions-and-resources/?time-period=medieval,early-modern,empire-and-industry,victorians,early-20th-century,interwar,second-world-war,postwar">Time periods</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/education/sessions-and-resources/?resource-type=lesson">Lessons</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/education/sessions-and-resources/?resource-type=workshop">Workshops</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/education/teachers/professional-development/">Professional development</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/education/teachers/">For teachers</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/education/students/">For students</a></li>
					</ul>
        </div>
      </nav>
      <nav class="col mega-menu-group clr">
        <div>
				<h3><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/help-with-your-research">Help with your research</a></h3>
					<ul>
					<li><a data-gtm="mega-menu" href="https://discovery.nationalarchives.gov.uk/">Search Discovery, our catalogue</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/help-with-your-research/start-here/">Start your research here</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/help-with-your-research/research-guides-keywords/">Research guides A-Z</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/help-with-your-research/research-guides/?research-category=online">Online collections</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/webarchive/">UK Government Web Archive</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/contact-us/british-citizenship-services/">British citizenship services</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/help-with-your-research/record-copying/">Record copying</a></li>
					</ul>
        </div>
      </nav>
      <nav class="col mega-menu-group clr">
        <div>
				<h3 class=hyphenate><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/">Information management</a></h3>
					<ul>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/browse-guidance-standards/">Guidance and standards A-Z</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">Copyright</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/manage-information/">How to manage your information</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/">Re-using PSI</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/producing-official-publications/">Producing official publications</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/legislation/">Legislation and regulations</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/information-management/training/">Training</a></li>
					</ul>
        </div>
      </nav>
      <nav class="col mega-menu-group clr">
        <div>
				<h3><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/archives-sector">Archives sector</a></h3>
					<ul>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/archives-sector/our-archives-sector-role/historical-manuscripts-commission/">Historical Manuscripts Commission</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/archives-sector/finding-funding/">Finding funding</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/archives-sector/projects-and-programmes/">Projects and programmes</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/archives-sector/case-studies-and-research-reports/">Case studies and research reports</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/archives-sector/advice-and-guidance/">Operating your archive</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/archives-sector/our-archives-sector-role/">Our role in the archives sector</a></li>
					</ul>
        </div>
      </nav>
      <nav class="col mega-menu-group clr">
        <div>
					<h3>More...</h3>
					<ul>
					<li><a data-gtm="mega-menu" href="https://shop.nationalarchives.gov.uk/">Shop</a></li>
					<li><a data-gtm="mega-menu" href="https://images.nationalarchives.gov.uk/">Image library</a></li>
					<li><a data-gtm="mega-menu" href="https://blog.nationalarchives.gov.uk/">Blog</a></li>
					<li><a data-gtm="mega-menu" href="https://media.nationalarchives.gov.uk/">Podcasts and videos</a></li>
					<li><a data-gtm="mega-menu" href="https://www.nationalarchives.gov.uk/contact-us/">Contact us</a></li>
					</ul>
        </div>
      </nav>
    </section>
  </div>
