<div id="main-navigation">
    <div class="accesskeys">
        <ul>
            <li><a href="#content" accesskey="s">Skip to content</a></li>
            <li><a href="/" accesskey="1">Home page</a></li>
            <li><a href="/help/a-to-z/" accesskey="3">A to Z index</a></li>
            <li><a href="/search/" accesskey="4">Search</a></li>
            <li><a href="/about/visit-us/" accesskey="5">Visit us</a></li>
            <li><a href="/help/" accesskey="6">Help</a></li>
            <li><a href="/contact-us/complaints-procedure/" accesskey="7">Complaints procedure</a></li>
            <li><a href="/legal/" accesskey="8">Terms of use</a></li>
            <li><a href="/contact-us/" accesskey="9">Contact us</a></li>
            <li><a href="/help/web-accessibility/" accesskey="0">Access key details</a></li>
        </ul>
    </div>
	
    <div id="main-menu-wrapper">
	
        <ul id="main-menu">
        <li id="first-left"><a href="/about/">About us</a></li><!--
    --><li><a href="/education/">Education</a></li><!--
    --><li><a href="/help-with-your-research/">Records</a></li><!--
    --><li><a href="/information-management/">Information management</a></li><!--
    --><li id="last-right"><a href="/archives-sector/">Archives sector</a></li>
<!-- <li id="last-right"><a href="/shop/">Shop online</a></li>
    -->
        </ul>
    </div>
</div>
<div class="accesskeys"><a id="content"></a></div>
