<link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
<link href="//fonts.googleapis.com/css?family=Bitter" rel="stylesheet" type="text/css">

<style type="text/css">
.newsletter-template {
	background: #dddddd;
	width: 100%;
	box-sizing: border-box;
	overflow: hidden; }
@media (max-width: 1155px) {
	.newsletter-template {
		border-left: 15px solid #008484; } }
.newsletter-template .news-icon {
	background: #008484;
	vertical-align: middle;
	text-align: center;
	width: 157px;
	height: 127px;
	display: inline-block;
	padding: 38px 0 0 0;
	float: left;
	overflow: hidden;
	box-sizing: border-box; }
.newsletter-template .news-icon img {
	width: 60px;
	height: 48px; }
@media (max-width: 1155px) {
	.newsletter-template .news-icon {
		display: none; } }
.newsletter-template .news-content {
	width: 45.879032258064516%;
	display: inline-block;
	float: left;
	overflow: hidden; }
.newsletter-template .news-content h3 {
	margin: 0;
	line-height: 31px;
	padding: 26px 0 0 20px;
	font-weight: 300;
	font-size: 24px;
	color:#000 !important;
	text-align:left;
	font-family: 'Bitter', serif; }
@media (max-width: 1155px) {
	.newsletter-template .news-content h3 {
		padding: 10px 15px 10px 20px; } }
@media (max-width: 974px) {
	.newsletter-template .news-content h3 {
		width: 100%;
		display: block; } }
.newsletter-template .news-content p {
	padding: 0 0 0 20px;
	margin-top:5px; }
@media (max-width: 1155px) {
	.newsletter-template .news-content p {
		padding: 0 0 0 20px;
	} }
@media (max-width: 974px) {
	.newsletter-template .news-content p {
		width: 100%;
		display: block;
		width:100%;} }
@media (max-width: 600px) {
	.newsletter-template .news-content p {
		width: 80%;
		display: block; } }
@media (max-width: 1155px) {
	.newsletter-template .news-content {
		width: 47%; } }
@media (max-width: 974px) {
	.newsletter-template .news-content {
		width: 100%;
		display: block; } }
.newsletter-template .news-form {
	width: 35.329032%;
	display: inline-block;
	padding: 25px 0 0 0;
	float: right; }
.newsletter-template .small-margin { margin-top:5px; }
.newsletter-template .small-margin a { text-decoration: none; }
.newsletter-template .news-form form label {
	display: none; }
.newsletter-template .news-form form input[type="email"] {
	width: 73% !important;
	height: 37px !important;
	padding-left:10px;
	margin:0;}
@media (max-width: 1155px) {
	.newsletter-template .news-form form input[type="email"] {
		margin-bottom: 10px; } }
@media (max-width: 370px) {
	.newsletter-template .news-form form input[type="email"] {
		width: 100%; } }
.newsletter-template .news-form form input[type="submit"] {
	height: 36px;
	border: none;
	background: #008484;
	color: #fff;
	font-size: 16px;
	padding: 0 10px 0 10px; }
@media (max-width: 1155px) {
	.newsletter-template .news-form {
		width: 48%; } }
@media (max-width: 974px) {
	.newsletter-template .news-form {
		padding: 0px 0 16px 20px;
		width: 70%;
		display: block;
		float: left; } }
@media (max-width: 370px) {
	.newsletter-template .news-form {
		width: 100%;
		padding-right: 10px; } }
.container  { 
    margin: 0 auto; 
    width: 100%;
}

#footer-wrapper {
    color: #FCFCFC;
    font-size: 1.25em;
    background: #333;
    min-height: 700px;
}

#footer-wrapper p {
    color: #FCFCFC;
}

#footer-wrapper a {
    text-decoration: none;
    color: #EFEFEF;
}

#footer-wrapper img {
    max-width: 80%;
}

.flickr-caption {
    font-size: 0.8em;
}

#footer-wrapper .call-to-action-link {
    color: #FFF;
}

#footer-wrapper h4 {
    font-family: 'Bitter', serif;
    font-weight: 400;
    font-size: 1.2em;
    margin-bottom: 0;
    color: #fff;
}

#footer-wrapper ul {
    margin: 10px 0;
    padding: 0;
    min-height: 220px;
}

#footer-wrapper li {
    list-style-type: none;
    padding: 0.5em 0;
    font-size: .85em;
    border-top: 1px dotted #666;
    width: 90%;
    font-family: 'Open Sans',sans-serif;
}

#footer-wrapper li:first-child {
    border: 0;
}
#footer-wrapper p {
    margin: 10px 0;
        font-family: 'Open Sans',sans-serif;
        line-height: 150%;
}
#footer-wrapper p img {
    max-width: 95%;
    margin: 10px 0 20px 0;
}
#footer-wrapper a {
    color: #FCE45C;
}
#footer-wrapper a:hover {
    text-decoration: underline;
}

.external-branding {
    margin: 0 20px;
    border-top: 1px dotted #545454;
    padding: 10px 0 20px 0;
    font-size: .85em;
}


.footer-base-external-branding-left {
    float: left;
width: 65%;
}

.footer-base-external-branding-left img {
    float: left;
    margin: 15px 25px 10px 0;
    }

.footer-base-external-branding-left p {
    display: block;
    float: left;
    margin: 0;
}

.footer-base-external-branding-right {
    float: right;
    width: 35%;
    text-align: right;
    margin: -5px -10px 0 0; /*adjustments to align with OGL logo on left hand side */
    padding: 0;
}



#footer-wrapper .call-to-action-link {
    color: #FFF;
}

.caption {
    font-size: .85em;
}


.starts-at-full {float: left;
    width: 100%;
}


.starts-at-quarter {float: left;
    width: 22.5%; 
    margin-left: 2%;        
}

    .col {
        margin-left: 2%; 
    }


    .ends-at-one-quarter { float: left;
        /*background-color: rgba(104, 135, 139, 1);*/
        width: 22.5%; 
margin-top: 20px;
    }


`
}


}

</style>
<div class="container">
        <div class="newsletter-template">
            <div class="news-icon">
                <img src="/wp-content/themes/tna-base/img/tna-newsletter-icon.png" alt="The National Archives Newsletter Icon">
            </div>

            <div class="news-content" id="newsletterAccessibility">
                <h3>Send me The National Archives’ newsletter</h3>
                <p>A monthly round-up of news, blogs, offers and events.</p>
            </div>

            <div class="news-form">
                <a href="https://www.nationalarchives.gov.uk/contact-us/email-updates/" class="call-to-action-link" style="background: #099;color: #fff;font-size: 1em;line-height: 130%;margin: 0 0 5px 0;padding: .5em;display: inline-block;">Sign up</a>
                <div class="small small-margin">
                    <a href="http://www.nationalarchives.gov.uk/legal/privacy-policy/" title="About our privacy policy">About our privacy policy</a>
                </div>
            </div>
        </div>
    </div>
<div id="footer-wrapper">
            <div class="container">
                

<div class="row">


                <div class="col starts-at-full ends-at-one-quarter clr">
            <h4>The National Archives</h4>
            <p>Kew<br/>Richmond<br/>TW9 4DU</p>
            
    </div>
   
   <div class="col starts-at-full ends-at-one-quarter clr">
    <div class="footer-left">
                <h4>Find out more</h4>
            <ul>
                <li><a href="/contact-us/">Contact us</a></li>
							<li><a href="/about/press-room/">Press room</a></li>
							<li><a href="/about/jobs/">Jobs and careers</a></li>
                <li><a href="/about/get-involved/friends-of-the-national-archives/">Friends of The National Archives</a></li>
            </ul>
    </div>
    <div class="footer-left">
                    <h4>Site help</h4>
        <ul>
            <li><a href="/help/">Help</a></li>
            <li><a href="/help/a-to-z/">Website A-Z index</a></li>
            <li><a href="/help/web-accessibility/">Accessibility</a></li>
        </ul>
     </div>

        </div>
       
    <div class="col starts-at-full ends-at-one-quarter clr">
      <div class="footer-left">
        <h4>Websites</h4>
        <ul>
            <li><a href="https://blog.nationalarchives.gov.uk/">Blog</a></li>
            <li><a href="https://media.nationalarchives.gov.uk/">Podcasts and videos</a></li>
            <li><a href="/webarchive/">UK Government Web Archive</a></li>
            <li><a href="https://www.legislation.gov.uk/"target="_blank" title="External website - link opens in a new window">Legislation.gov.uk</a></li>
            <li><a href="https://caselaw.nationalarchives.gov.uk/">Find case law</a></li>
            <li><a href="https://www.thegazette.co.uk/"target="_blank" title="External website - link opens in a new window">The Gazette</a></li>
        </ul>
      </div>
      <div class="footer-left">
                <h4>Legal</h4>
        <ul>
            <li><a href="/legal/">Terms of use</a></li>
							<li><a href="/legal/privacy-policy">Privacy policy</a></li>
            <li><a href="/legal/cookies/">Cookies</a></li>
            <li><a href="/about/freedom-of-information/">Freedom of Information</a></li>
							<li><a href="/about/our-role/transparency/">Transparency</a></li>
                        <li><a href="/legal/our-fees/">Our fees</a></li>

        </ul>
      </div>
    </div>
                
 <div class="col starts-at-full ends-at-one-quarter clr">
    <div class="footer-left">
            <h4>Follow us</h4>
            <ul>
                <li><a href="https://twitter.com/@UKNatArchives"target="_blank" title="External website - link opens in a new window">Twitter</a></li>
                <li><a href="https://www.youtube.com/c/TheNationalArchivesUK"target="_blank" title="External website - link opens in a new window">YouTube</a></li>
                <li><a href="http://flickr.com/photos/nationalarchives"target="_blank" title="External website - link opens in a new window">Flickr</a></li>
                <li><a href="http://facebook.com/TheNationalArchives"target="_blank" title="External website - link opens in a new window">Facebook</a></li>
                <li><a href="https://commons.wikimedia.org/wiki/Commons:The_National_Archives_(United_Kingdom)" target="_blank" title="External website - link opens in a new window">Wikimedia Commons</a></li>
                <li><a href="/rss/">RSS</a></li>
            </ul>
    </div>
                <div class="footer-left">
                </div>

</div>




</div> <!-- row --> 


<div class="row external-branding">

    <div class="footer-base-external-branding-left">
 <a href="/doc/open-government-licence/"><img alt="Open Government License logo" src="/images/global/logo-ogl.png"></a><p>All content is available under the <a href="/doc/open-government-licence/">Open Government Licence v3.0</a>, <br/>except where otherwise stated</p> 
</div>

 <div class="footer-base-external-branding-right">
 <a target="_blank" title="External website - opens in a new window" href="http://gov.uk" class="footer-base-external-branding-gov-logo-adjust"><img alt="GOV.UK logo" src="/images/global/gov-uk.png"/></a>
</div>
                

</div>  <!-- row external branding -->      
</div> <!-- container -->
        </div> <!-- footer-wrapper -->

<script>
$(document).ready(function() {

	/*
	 * The National Archives
	 * Author:  Mihai Diaconita - WEB TEAM
	 * Newsletter Back To Origin Jquery plugin
	 * */
	(function ($) {
		$.fn.newsletterBackToOrigin = function (options) {
			var settings = $.extend({}, $.fn.newsletterBackToOrigin.defaults, options);
			return this.each(function () {
				var thankYouURL = "http://www.nationalarchives.gov.uk/about/get-involved/newsletters/the-national-archives-newsletter/thank-you/",
					newValue = "?oldurl=" + window.location.href;
				return settings.$element.val(thankYouURL + newValue);
			});
		}

		// Default settings
		$.fn.newsletterBackToOrigin.defaults = {
			$element: $('input[name="ReturnURL"]'),
		}
	}(jQuery));

// Make sure the signup newsletter form matches the ID below
// By default target element is $('input[name="ReturnURL"]')
	$('#signup').newsletterBackToOrigin();
	
});
</script>
