<div id="top_banner">

	<div id="logo"><img src="/images/global/logo.gif" alt="The National Archives" width="118" height="73" align="left" /></div>

	<div class="pop-util">

		<script language = "javascript" type="text/javascript">
		<!--
			document.writeln("<a href=\"#\" onclick=\"tna_print(); return false;\"><img src=\"/images/buttons/popup_print.gif\" alt=\"Print page\" width=\"64\" height=\"20\" border=\"0\" /><\/a>")
			document.writeln("<a href=\"javascript:window.close();\" accesskey=\"k\"><img src=\"/images/buttons/popup_close.gif\" alt=\"Close window\" border=\"0\" width=\"106\" height=\"20\" /><\/a><br />");
		//-->
		</script>

		<noscript>
			To print this page press:<br />
			<b>Ctrl</b> + <b>P</b> (on a PC) or <b>Command</b> + <b>P</b> (on a Mac)
		</noscript>
	</div>

</div>