<div id="main-navigation">
	<div class="accesskeys">
		<ul>
			<li><a href="#content" accesskey="s">Skip to content</a></li>
			<li><a href="/" accesskey="1">Home page</a></li>
			<li><a href="/help/atoz.htm" accesskey="3">A to Z index</a></li>
			<li><a href="/search" accesskey="4">Search</a></li>
			<li><a href="/visit" accesskey="5">Visit us</a></li>
			<li><a href="/help" accesskey="6">Help</a></li>
			<li><a href="/contact/complaints.htm" accesskey="7">Complaints procedure</a></li>
			<li><a href="/legal" accesskey="8">Terms of use</a></li>
			<li><a href="/contact" accesskey="9">Contact us</a></li>
			<li><a href="/help/accesskeys.htm" accesskey="0">Access key details</a></li>
		</ul>
	</div>
	<div id="main-menu-wrapper">
       <ul id="main-menu">
            <li id="first-left"><a accesskey="i" href="/about/">About us</a>
			</li>
            <li><a accesskey="5" href="/education/">Education</a>
			</li>
            <li><a accesskey="x" href="/records/">Records</a>
			</li>
            <li><a accesskey="m" href="/information-management/">Information management</a>
			</li>
			<li><a accesskey="" href="/archives-sector/">Archives sector</a>
			</li>
           <li id="last-right"><a accesskey="p" href="/shop/" class="selected">Shop online</a></li>           
        </ul>
	</div>
	</div>	
	<div id="sub-menu-wrapper"  class="shop">
	<ul id="sub-menu">
		<li><a href="/bookshop/">Bookshop</a></li>
		<li><a href="/records/our-online-records.htm/">Our online records</a></li>
		<li><a href="/recordcopying/">Record copying</a></li>
		<li class="no-border"><a href="https://images.nationalarchives.gov.uk/">Image library</a></li>
	</ul>
	</div>
	<div class="accesskeys"><a id="content"> </a></div>
