<div id="footer">
		<div class="minHeight"></div>
		<div id="footer-content">
			<ul>
				<li><a href="/contact-us/" target="_blank">Contact Us</a></li>
				<li><a href="/education/worldwar2/credits/index.htm">Credits</a></li>
				<li><a href="/education/worldwar2/help/index.htm">Help</a></li>												
				<li><a href="/education/worldwar2/teachers/index.htm">Teacher's Notes</a></li>										
				<li><a href="/education/worldwar2/glossary/index.htm">Glossary</a></li>
                <li class="last"><a href="/education/worldwar2/help/index.htm#filesizes">File sizes</a></li>
			</ul>
		</div>
		<div class="clear"></div>
	</div>
