<div id="breadcrumbdiv"><a href="http://www.nationalarchives.gov.uk" target="_top"><img src="/images/micrositea.gif" width="44" height="30" alt="The National Archives" align="middle"  border="0"></a><a href="http://www.nationalarchives.gov.uk" class="bbreadcrumb" target="_top">The National Archives</a><span class="bbreadcrumb">&nbsp;&gt;&nbsp;</span><a href="/education/" class="bbreadcrumb" target="_top">Education</a><span class="bbreadcrumb">&nbsp;&gt;&nbsp;</span><a href="/education/focuson/film/" class="bbreadcrumb" target="_top">Focus on Film</a></div>

  <style type="text/css">

    #failover {
        background-color: #FCE45C;
        padding: .3em 2em;
        text-align: center;
        border: dashed #000 1px;
    }

    #failover h2 {
      color: #000!important;
      margin: 6px;
      font-size: 18px;
    }

    #failover p {
      margin: 6px;
      font-size: 15px;
    }

    #failover a {
      text-decoration: underline!important;
    }

    @media only screen and (max-width:480px) {

    #failover p {
      font-size: .8em;
    }

    }

    </style>
   <div id="failover">
    <p>The interactive parts of this resource no longer work, but it has been archived so you can continue using the rest of it.</p></div>
