<div id="breadcrumbdiv">
<a href="/"><img src="/images/micrositea.gif" width="44" height="30" alt="The National Archives" align="middle" class="blackbreadcrumb" border="0"></a>

<a href="/" class="bbreadcrumb">The National Archives</a><span class="bbreadcrumb"> > </span>

<a href="/gettingstarted/" class="bbreadcrumb">Research and learning</a><span class="bbreadcrumb"> > </span>

<a href="/education/" class="bbreadcrumb">Education</a><span class="bbreadcrumb"> > </span>



<a href="/education/focuson/document/" class="bbreadcrumb">How to Read a Document</a></div>