<ul class="footer">
	<li class="first-child"><a href="/education/focuson/film/credits.htm" class="credits">Credits</a></li>
	<li><a href="/education/focuson/film/help.htm" class="help">Help</a></li>
	<li><a href="/education/focuson/film/teachers-notes.htm" class="teachers-notes">Teacher&prime;s notes</a></li>
	<li><a href="http://www.nationalarchives.gov.uk/educationservice/ks3.htm#a1" class="workshops">Workshops</a></li>
	<li><a href="/education/focuson/film/site-map.htm" class="site-map">Sitemap</a></li>	
	<li class="back-to-top"><a href="#top">Back to Top</a></li>	            
</ul>