<ul id="jumplinks">
	<li><a href="#content-start" accesskey="s">Skip navigation</a></li>
	<li><a href="http://www.nationalarchives.gov.uk/education/focuson/film/default.htm" accesskey="1">Home page</a></li>
	<li><a href="http://www.nationalarchives.gov.uk/education/focuson/film/site-map.htm" accesskey="3">Site map</a></li>
	<li><a href="http://www.nationalarchives.gov.uk/education/focuson/film/help.htm" accesskey="6">Help</a></li>
	<li><a href="http://www.nationalarchives.gov.uk/contact/" accesskey="9">Feedback form</a></li>
	<li><a href="http://www.nationalarchives.gov.uk/education/focuson/film/accesskeys.htm" accesskey="0">Access key details</a></li>
</ul>