<ul>
	<li><a href="/education/focuson/film/" class="home">Home</a></li>
	<li><a href="/education/focuson/film/introduction/" class="introduction">Introduction</a></li>
	<li><a href="/education/focuson/film/activities/" class="activities">Activities</a></li>
	<li><a href="/education/focuson/film/film-archive/" class="film-archive">Film Archive</a></li>
	<li><a href="/education/focuson/film/editors-room/" class="editors-room">Editor&prime;s Room</a></li>
	<li><a href="/education/focuson/film/help.htm" class="help">Help</a></li>
</ul>