<meta name="DC.title" content="Focus on Film" />

<meta name="DC.rights" content="http://www.nationalarchives.gov.uk/legal/copyright.htm" />

<meta name="DC.publisher" content="The National Archives, Kew, Surrey TW9 4DU" />

<meta name="DC.creator" content="The National Archives" />

<meta name="DC.language" scheme="ISO 639-2/T" content="eng" />

<meta name="DC.format" scheme="DCTERMS.IMT" content="text/html" />

<meta name="DC.date.created" scheme="DCTERMS.W3CDTF" content="2006-03-01" />

<meta name="DC.date.modified" scheme="DCTERMS.W3CDTF" content="2006-03-01" />

<meta name="DC.coverage.temporal" content="1916-1945" /> 

<meta name="eGMS.subject.category" scheme="GCL" content="Libraries and archives" />

<meta name="eGMS.subject.keyword" content="National Archives, South East Grid for Learning, film, film clips, film archive, film evidence, historical source, film maker, film sponsor, activities, interactive whiteboard, online editing tool, film editor, Key stage 2 to 5" />

<meta name="keywords" content=" National Archives, South East Grid for Learning, film, film clips, film archive, film evidence, historical source, film maker, film sponsor, activities, interactive whiteboard, online editing tool, film editor, Key stage 2 to 5 " />

<meta name="DC.description" content=" This Focus On presents film as a historical source and considers its advantages as evidence for the past. There are activities to investigate aspects of film as evidence. Access these on a pc or via an interactive whiteboard. There is a film archive with background information on each film. Film can be downloaded for free. Work in our editor’s room and use our online film-editing tool to create your own clips." />

<meta name="description" content=" This Focus On presents film as a historical source and considers its advantages as evidence for the past. There are activities to investigate aspects of film as evidence. Access these on a pc or via an interactive whiteboard. There is a film archive with background information on each film. Film can be downloaded for free. Work in our editor’s room and use our online film-editing tool to create your own clips." />

