<div id="EROheader">

	<h1>Electronic Records Online</h1>

	<ul>

		<li>
			<a href="/ero/default.aspx">
				<img src="/images/appmenu/welcome_off.gif" width="90" height="20" alt="Welcome" /></a>
		</li>

		<li>
			<a href="/aboutapps/ero2/about.htm">
				<img src="/images/appmenu/about_off.gif" width="57" height="20" alt="About" /></a>
		</li>

		<li>
			<a href="/help/ero2/">
				<img src="/images/appmenu/help_off.gif" width="52" height="20" alt="Help" /></a>
			<br />
		</li>

		<li id="searchheaderlink" style="visibility:hidden">
			<a href="/ero/search.aspx">
				<img src="/images/appmenu/search_off.gif" width="72" height="20" alt="Search" /></a>
		</li>

		<li>
			<a href="/ero/browse.aspx">
				<img src="/images/appmenu/browse_off.gif" width="78" height="20" alt="Browse" /></a>
		</li>

	</ul>

	<script language="javascript" type="text/javascript">
		document.getElementById('searchheaderlink').style.visibility = 'visible';
	</script>

</div>