			<dl>
				<dt id="abolition">Abolition</dt>
				<dd>The campaign to abolish the British slave trade in British territories. ‘An Act for the Abolition of the Slave Trade’ was passed by Parliament on March 25 1807, which officially abolished the slave trade in the British Empire, though ‘illegal’ slave trading continued. </dd>
				
				<dt id="american_civil_war">American Civil War</dt>
				<dd>The war which occurred in North America between 1861 and 1865. It was a conflict that began after the southern states of the United States seceded from the Union and formed the Confederate States of America, in order for the South to preserve slavery. It resulted in a victory to the Union and the abolition of slavery in the United States of America.</dd>
				
				<dt id="american_revolution">American Revolution</dt>
				<dd>The revolution occurred in the late 18th century, and is also referred to as the American Revolutionary War or the American War of Independence.  In 1776, it resulted in the political independence of 13 colonies in North America after 200 years of rule under the British, thus creating the United States of America.</dd>
				
				<dt id="apprenticeship">Apprenticeship</dt>
				<dd>This word is used in general terms to describe the position of an apprentice working under a legal agreement for a low wage as an initiatory training in a trade. The apprenticeship system was applied to previously enslaved people, between 1834 and 1838, who were forced to work as ‘apprentices’ for their old ‘masters’. This system was not implemented in all Caribbean islands. </dd>
					
				<dt id="black_carib">Black Carib </dt>
				<dd>This was the term initially used by colonial elites and the colonial government to describe people of mixed African and indigenous Carib heritage.</dd>
				
				<dt id="brigands_war">Brigands’ War </dt>
				<dd>This war took place in the Windward Islands, between 1794 and 1798, and is also called 'The Second Carib War'. One island caught in this conflict was St Vincent, where ‘Black Carib’ chief Chatoyer led a revolution which lasted until June 1796.</dd>
				
				<dt id="british_empire">British Empire </dt>
				<dd>Countries throughout the world conquered or settled by England/Great Britain during the period from the 16th to the 20th centuries.  Most had achieved independence by the end of the 20th century, and many are now members of the Commonwealth.  </dd>
				
				<dt id="carib">Carib </dt>
				<dd>Term imposed on the various indigenous peoples of the Caribbean islands and parts of Central and South America by Europeans on their arrival to the region. Carib also refers to people of duel indigenous and African descent.   </dd>

				<dt id="the_caribbean">Caribbean</dt>
				<dd>A region of the Americas comprised of the Caribbean Sea, its islands and the mainland surrounding it. [This exhibition looks mainly at the Caribbean region but also includes Bermuda].</dd>	
							
				<dt id="cartel">Cartel </dt>
				<dd>An agreement or association between two or more business houses for regulating output, fixing prices, etc. Also, the businesses thus combined; a trust or syndicate.</dd>
				
				<dt id="chattel_slavery">Chattel Slavery</dt>
				<dd>System of slavery whereby an individual and their offspring are recognised by the law as being the property of another person for life. This system was established by Europeans and formed the basis of <a href="#Transatlantic_Slave_Trade">transatlantic slavery</a>.</dd>
				
				<dt id="colonial_administrators">Colonial administrators  </dt>
				<dd>Civil servants appointed locally, or from London, to run the colonial governments. </dd>
				
				<dt id="coloured">Coloured</dt>
				<dd>This term was used in the colonial period usually to describe people of mixed African and white heritage, by white colonialists and by people describing themselves. Its precise definition changes however according to time and place. </dd>
					
				<dt id="convict_establishment">Convict Establishment  </dt>
				<dd>A place where people serving penal sentences were kept or sent – this was often in the colonies.</dd>
				
				<dt id="constitution">Constitution</dt>
				<dd>The mode in which a state is constituted or organised.</dd>
				
				<dt id="diaspora">Diaspora</dt>
				<dd>This term historically refers to a ‘scattered people’. The traditional definition refers to any dispersed community which has members residing in at least two outlying areas, as well as a centre of origin. Today it is generally, though not exclusively, used to describe communities not confined by national borders. </dd>
				
				<dt id="emancipation">Emancipation</dt>
				<dd>To set free from control; the term given to the abolition of slavery wherein the freedom of enslaved people was enacted. </dd>				
				
				<dt id="enslaved_people">Enslaved people</dt>
				<dd>This term refers to somebody who has been enslaved; and in the context of this exhibition refers to people who were enslaved under the chattel system operating in the Americas during the period of <a href="#Transatlantic_Slave_Trade">transatlantic slavery</a>. ‘Enslaved’ means the same as ‘slave’, but is the term now preferred by some as it denotes a less passive status.  </dd>
				
				<dt id="enslaved_africans">Enslaved Africans </dt>
				<dd>People of African heritage who were enslaved under the chattel system operating in the Americas during the period of slavery.</dd>
				
				<dt id="european_powers">European powers</dt>
				<dd>The dominant European countries involved in trade, overseas expansion and colonialism. </dd>
					
				<dt id="fedon_revolution">F&eacute;don Revolution</dt>
				<dd>A term used to describe a period in Grenada between 1795 and 1796 when Julien F&eacute;don led a revolution against British rule and slavery. The revolutionaries were comprised of French speaking free people of colour and enslaved people.</dd>

				
				<dt id="garveyism">Garveyism</dt>
				<dd>A 20th century movement based on the ideas of Marcus Garvey, a Jamaican, who promoted the Black Nationalism movement. </dd>
				
				<dt id="haitian_revolution">Haitian Revolution</dt>
				<dd>The only successful ‘slave revolt’, which occurred between 1791 and 1801, leading to Haiti becoming the world’s first free black nation in the western hemisphere. </dd>
				
				<dt id="indentured_labour">Indentured labour</dt>
				<dd>Workers bound by contracts stipulating that their labour is given to a specific employer for a fixed period of time. Such contracts are usually enforced by criminal law.</dd>
				
				<dt id="indigenous">Indigenous</dt>
				<dd>Born, or produced naturally, in a land or region. </dd>
				
				<dt id="legislature">Legislature</dt>
				<dd>A body of people invested with the power to make the laws of a country or state.</dd>
				
				<dt id="liberated_africans">Liberated Africans</dt>
				<dd>Enslaved Africans freed from illegal slave trading vessels after the abolition of the British slave trade in 1807. They were often sent by the British authorities to St Helena and then usually either transported to Sierra Leone, or sent to work as indentured labourers on islands in the Caribbean. </dd>
					
				<dt id="maroons">Maroons</dt>
				<dd>Runaway slaves (and descendants) living in autonomous communities in the Americas.  <em>Maroon</em> derives from the Spanish word <em lang="es" xml:lang="es">cimarron</em>, which originally referred to escaped domestic cattle. </dd>
				
				<dt id="morant_bay_rebellion">Morant Bay rebellion </dt>
				<dd>A major rebellion which took place in Jamaica in 1865.  The rebellion started in Morant Bay, in the parish of St. Thomas, and was an important turning point for Jamaican society.</dd>
				
				<dt id="mulatto">Mulatto </dt>
				<dd>A person who has one African and one European parent; although it is also used more generally to describe a person of mixed black and white heritage.</dd>
				
				<dt id="nationalism">Nationalism</dt>
				<dd>The promotion of one’s own nation. In the context of colonialism, it is a term used by those wishing to gain  freedom from imperial rule and national independence.</dd>									

				<dt id="obeah">Obeah </dt>
				<dd>The practice of folk medicine and religion originating in West Africa, which has been found throughout the Caribbean since the time of slavery.</dd>
					
				<dt id="pan-africanism">Pan-Africanism</dt>
				<dd>A movement which encouraged unity between Africans and those of the African diaspora, and fought for independence from colonial rule. Leading pan-Africanists include W. E. B. Du Bois, Sylvester Williams, George Padmore, and Amy Garvey.</dd>
				
				<dt id="panama_canal">Panama Canal</dt>
				<dd>A man-made waterway which was cut through the Isthmus of Panama in order to provide a shipping route between the Atlantic and Pacific Oceans.</dd>
				
				<dt id="plantation">Plantation</dt>
				<dd>An estate used to grow large scale crops such as sugar cane or cotton, on which slaves and indentured labourers worked.</dd>
				
				<dt id="plantation_system">Plantation system</dt>
				<dd>A method of dividing land into private estates, which were worked on by enslaved people who were the ‘property’ of the estate owners.</dd>
				
				<dt id="prohibition">Prohibition</dt>
				<dd>A ban on an activity; in this case a legal ban by the United States of America, on the importation, manufacture, exportation and sale of alcohol (1920-1933).</dd>
				
				<dt id="resistance">Resistance</dt>
				<dd>A force of opposition; in this case against the institution of slavery. Resistance was displayed in many ways from refusal to work and running away, through to violent uprisings and the formation of independent communities which existed outside of the plantation system.</dd>
				
				<dt id="telegraph">Telegraph </dt>
				<dd>A method of communicating messages over great distances using cables or radio. </dd>
					
				<dt id="transatlantic_slave_trade">Transatlantic Slave Trade </dt>
				<dd>The trade by Europeans of enslaved people from Africa to the Americas, across the Atlantic Ocean. Also referred to as the ‘triangular trade’ which describes three points of the trade route between Europe, Africa and the Caribbean. </dd>
				
				<dt id="transported">Transported</dt>
				<dd>To convey people from one place to another; in this case transported refers to the carrying of convicts.</dd>
				
				<dt id="unionisation">Unionisation </dt>
				<dd>A movement in which workers come together to demand better wages and working conditions.</dd>
				
				<dt id="west_india_regiment">West India Regiment</dt>
				<dd>A British colonial infantry regiment which was comprised mainly of freed slaves from North America, and enslaved persons from the West Indies and Africa. After the end of the slave trade, the regiment included freed slaves from West Africa and Caribbean and African recruits. Initially raised in 1795 and finally disbanded in 1927.</dd>
				
				<dt id="yellow_carib">Yellow Carib</dt>
				<dd>A term used in St. Vincent, and possibly elsewhere, by the colonial authorities to describe those of indigenous heritage, in opposition to Black Caribs, who had dual African and indigenous heritage. </dd>	
				
			</dl>