<table width="100%" border="0" cellspacing="0" cellpadding="0" summary="table for layout">	
  <tr>
    <td colspan="3"><img src="/images/pixels/pixeltrans.gif" alt="" width="1" height="10" /></td>
  </tr>
  <tr>
    <td colspan="3" class="thindots"><img src="/images/pixels/pixeltrans.gif" alt="" width="1" height="1" /></td>
  </tr>
  <tr>
    <td colspan="3"><img src="/images/pixels/pixeltrans.gif" alt="" width="1" height="5" /></td>
  </tr>
	<tr>
    <td width="2%">&nbsp;</td>
    <td width="96%">
      <table width="282" align="right" border="0" cellspacing="0" cellpadding="0" summary="table for layout">
        <tr>
					<td><a href="#top"><img src="/battles/images/popup_topofpage_rust.gif" alt="Go to top of page" border="0" width="92" height="20" align="left" /></a></td>
          <td><img src="/images/pixels/pixeltrans.gif" alt="" width="10" height="8" /></td>
          <td valign="top">
						<noscript>To print (for PC users), press <b>Ctrl</b> 
						+ <b>P</b> key.<br />
						To print (for MAC users), press <b>Command</b> + <b>P</b> 
						key.<br />
						</noscript>
						<a href="#" onkeypress="this.onclick()" onclick="tna_print()"><img src="/battles/images/popup_print_rust.gif" alt="Print page" width="64" height="20" border="0" /></a>
		  </td>
          <td><img src="/images/pixels/pixeltrans.gif" alt="" width="10" height="8" /></td>
					<td valign="top"><a href="javascript:window.close();" accesskey="k"><img src="/battles/images/popup_close_rust.gif" alt="Close window" border="0" width="106" height="20" align="right" /></a></td>
        </tr>
      </table>
		</td>
    <td width="2%">&nbsp;</td>
  </tr>
</table>