<table width="100%"  border="0" cellspacing="0" cellpadding="0" summary="table for layout">
  <tr>
    <td><img src="/images/global/logo_black.gif" alt="The National Archives" width="118" height="73" align="left" />
	</td>
    <td colspan="2"><span class="trafalgarheading"><img src="/nelson/images/heading_popup.gif" alt="Trafalgar Ancestors" width="213" height="38" border="0" /></span></td>
    <td valign="top">
      <table width="170" align="right" border="0" cellspacing="0" cellpadding="0" summary="table for layout">
        <tr>
          <td valign="top">
						<noscript>To print (for PC users), press <b>Ctrl</b> 
						+ <b>P</b> key.<br />
						To print (for MAC users), press <b>Command</b> + <b>P</b> 
						key.<br />
						</noscript>
						<a href="#" onkeypress="this.onclick()" onclick="tna_print()"><img src="/images/buttons/popup_print_green.gif" alt="Print page" width="64" height="20" border="0" class="valigntop" /></a>
		  </td>
          <td><img src="/images/pixels/pixeltrans.gif" alt="" width="10" height="8" /></td>
					<td valign="top"><a href="javascript:window.close();" accesskey="k"><img src="/images/buttons/popup_close_green.gif" alt="Close window" border="0" width="106" height="20" align="right" class="valigntop" /></a></td>
        </tr>
      </table>
	</td>
    <td valign="top" width="2%">&nbsp;</td>
  </tr>
  <tr>
    <td colspan="5" class="thindots"><img src="/images/pixels/pixeltrans.gif" alt="" width="1" height="1" /></td>
  </tr>
  <tr>
    <td colspan="5"><img src="/images/pixels/pixeltrans.gif" alt="" width="1" height="5" /></td>
  </tr>
</table>